using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;




public class FinPartie : MonoBehaviour
{
    public GameObject Carte1;
    public GameObject Carte2;
    public GameObject Carte3;
    public GameObject Carte4;
    public GameObject Carte5;
    public GameObject Carte6;
    public GameObject Carte7;
    public GameObject Carte8;
    public GameObject Carte9;
    public GameObject Carte10;
    public GameObject Carte11;
    public GameObject Carte12;
    public GameObject Carte13;
    public GameObject Carte14;
    public GameObject Carte15;
    public GameObject Carte16;
    public GameObject Carte17;
    public GameObject Carte18;
    public GameObject Carte19;
    public GameObject Carte20;
    public GameObject Carte21;
    public GameObject Carte22;
    public GameObject Carte23;
    public GameObject Carte24;
    public GameObject Carte25;
    public GameObject Carte26;
    public GameObject Carte27;
    public GameObject Carte28;
    public GameObject Carte29;
    public GameObject Carte30;
    public GameObject Carte31;
    public GameObject Carte32;
    public GameObject Carte33;
    public GameObject Carte34;
    public GameObject Carte35;
    public GameObject Carte36;
    public GameObject Carte37;
    public GameObject Carte38;
    public GameObject Carte39;
    public GameObject Carte40;
    public GameObject Carte41;
    public GameObject Carte42;
    public GameObject Carte43;
    public GameObject Carte44;
    public GameObject Carte45;
    public GameObject Carte46;
    public GameObject Carte47;
    public GameObject Carte48;
    public GameObject Carte49;
    public GameObject Carte50;
    public GameObject Carte51;
    public GameObject Carte52;
    public GameObject Carte53;
    public GameObject Carte54;
    public GameObject Carte55;
    public GameObject Carte56;
    public GameObject Carte57;
    public GameObject Carte58;
    public GameObject Carte59;
    public GameObject Carte60;
    public GameObject Carte61;
    public GameObject Carte62;
    public GameObject Carte63;
    public GameObject Carte64;
    public GameObject Carte65;
    public GameObject Carte66;
    public GameObject Carte67;
    public GameObject Carte68;
    public GameObject Carte69;
    public GameObject Carte70;
    public GameObject Carte71;
    public GameObject Carte72;
    public GameObject Carte73;
    public GameObject Carte74;
    public GameObject Carte75;
    public GameObject Carte76;
    public GameObject Carte77;
    public GameObject Carte78;
    public GameObject Carte79;
    public GameObject Carte80;

    public GameObject Gagné;
    public GameObject Perdu;
    public GameObject VictoireJ1;
    public GameObject VictoireJ2;
    public GameObject VictoireIA;
    public GameObject Egalité;

    public Animator carte1;
    public Animator carte2;
    public Animator carte3;
    public Animator carte4;
    public Animator carte5;
    public Animator carte6;
    public Animator carte7;
    public Animator carte8;
    public Animator carte9;
    public Animator carte10;
    public Animator carte11;
    public Animator carte12;
    public Animator carte13;
    public Animator carte14;
    public Animator carte15;
    public Animator carte16;
    public Animator carte17;
    public Animator carte18;
    public Animator carte19;
    public Animator carte20;
    public Animator carte21;
    public Animator carte22;
    public Animator carte23;
    public Animator carte24;
    public Animator carte25;
    public Animator carte26;
    public Animator carte27;
    public Animator carte28;
    public Animator carte29;
    public Animator carte30;
    public Animator carte31;
    public Animator carte32;
    public Animator carte33;
    public Animator carte34;
    public Animator carte35;
    public Animator carte36;
    public Animator carte37;
    public Animator carte38;
    public Animator carte39;
    public Animator carte40;
    public Animator carte41;
    public Animator carte42;
    public Animator carte43;
    public Animator carte44;
    public Animator carte45;
    public Animator carte46;
    public Animator carte47;
    public Animator carte48;
    public Animator carte49;
    public Animator carte50; 
    public Animator carte51;
    public Animator carte52;
    public Animator carte53;
    public Animator carte54;
    public Animator carte55;
    public Animator carte56;
    public Animator carte57;
    public Animator carte58;
    public Animator carte59;
    public Animator carte60; 
    public Animator carte61;
    public Animator carte62;
    public Animator carte63;
    public Animator carte64;
    public Animator carte65;
    public Animator carte66;
    public Animator carte67;
    public Animator carte68;
    public Animator carte69;
    public Animator carte70; 
    public Animator carte71;
    public Animator carte72;
    public Animator carte73;
    public Animator carte74;
    public Animator carte75;
    public Animator carte76;
    public Animator carte77;
    public Animator carte78;
    public Animator carte79;
    public Animator carte80;


    public MemoryCheck memcheck;
    public CarteRandomizer carterandomUES;
    public ESMemoryCheck ESmemcheck;
    public ESCarteRandomizer carterandomES;
    public NRMemoryCheck NRmemcheck;
    public NRCarteRandomizer carterandomNR;
    public HDMemoryCheck HDmemcheck;
    public HDCarteRandomizer carterandomHD;
    public UHDMemoryCheck UHDmemcheck;
    public UHDCarteRandomizer carterandomUHD;

    public void RetourMenu()
    {

        SceneManager.LoadScene("MenuPrincipal");

    }

    public void Rejouer()
    {

        carterandomUES.Mélangeur();
        memcheck.vies = 5;
        memcheck.paires = 0;
        memcheck.points = 0;
        memcheck.pointsJ1 = 0;
        memcheck.pointsJ2 = 0;
        memcheck.pointsIA = 0;
        memcheck.AfficherPoints();
        memcheck.Affichepoints.text = memcheck.AfficherPoints();
        memcheck.AfficherPointsJ1();
        memcheck.AffichepointsJ1.text = memcheck.AfficherPointsJ1();
        memcheck.AfficherPointsJ2();
        memcheck.AffichepointsJ2.text = memcheck.AfficherPointsJ2();
        memcheck.AfficherVies();
        memcheck.Affichevies.text = memcheck.AfficherVies();
        Carte1.SetActive(true);
        Carte2.SetActive(true);
        Carte3.SetActive(true);
        Carte4.SetActive(true);
        Carte5.SetActive(true);
        Carte6.SetActive(true);
        Carte7.SetActive(true);
        Carte8.SetActive(true);
        Carte9.SetActive(true);
        Carte10.SetActive(true);
        
        carte1.enabled = true;
        carte2.enabled = true;
        carte3.enabled = true;
        carte4.enabled = true;
        carte5.enabled = true;
        carte6.enabled = true;
        carte7.enabled = true;
        carte8.enabled = true;
        carte9.enabled = true;
        carte10.enabled = true;

        Gagné.SetActive(false);
        Perdu.SetActive(false);
        VictoireJ1.SetActive(false);
        VictoireJ2.SetActive(false);
        VictoireIA.SetActive(false);
        Egalité.SetActive(false);
    }
    

    public void RejouerES()
    {

        carterandomES.Mélangeur();
        ESmemcheck.vies = 10;
        ESmemcheck.paires = 0;
        ESmemcheck.points = 0;
        ESmemcheck.pointsJ1 = 0;
        ESmemcheck.pointsJ2 = 0;
        ESmemcheck.pointsIA = 0;
        Debug.Log(ESmemcheck.points);
        ESmemcheck.AfficherPoints();
        ESmemcheck.Affichepoints.text = ESmemcheck.AfficherPoints();
        ESmemcheck.AfficherPointsJ1();
        ESmemcheck.AffichepointsJ1.text = ESmemcheck.AfficherPointsJ1();
        ESmemcheck.AfficherPointsJ2();
        ESmemcheck.AffichepointsJ2.text = ESmemcheck.AfficherPointsJ2();
        ESmemcheck.AfficherVies();
        ESmemcheck.Affichevies.text = ESmemcheck.AfficherVies();
        Carte1.SetActive(true);
        Carte2.SetActive(true);
        Carte3.SetActive(true);
        Carte4.SetActive(true);
        Carte5.SetActive(true);
        Carte6.SetActive(true);
        Carte7.SetActive(true);
        Carte8.SetActive(true);
        Carte9.SetActive(true);
        Carte10.SetActive(true);
        Carte11.SetActive(true);
        Carte12.SetActive(true);
        Carte13.SetActive(true);
        Carte14.SetActive(true);
        Carte15.SetActive(true);
        Carte16.SetActive(true);
        Carte17.SetActive(true);
        Carte18.SetActive(true);
        Carte19.SetActive(true);
        Carte20.SetActive(true);

        carte1.enabled = true;
        carte2.enabled = true;
        carte3.enabled = true;
        carte4.enabled = true;
        carte5.enabled = true;
        carte6.enabled = true;
        carte7.enabled = true;
        carte8.enabled = true;
        carte9.enabled = true;
        carte10.enabled = true;
        carte11.enabled = true;
        carte12.enabled = true;
        carte13.enabled = true;
        carte14.enabled = true;
        carte15.enabled = true;
        carte16.enabled = true;
        carte17.enabled = true;
        carte18.enabled = true;
        carte19.enabled = true;
        carte20.enabled = true;


        Gagné.SetActive(false);
        Perdu.SetActive(false);
        VictoireJ1.SetActive(false);
        VictoireJ2.SetActive(false);
        VictoireIA.SetActive(false);
        Egalité.SetActive(false);
    }

    public void RejouerNR()
    {

        carterandomNR.Mélangeur();
        NRmemcheck.vies = 20;
        NRmemcheck.paires = 0;
        NRmemcheck.points = 0;
        NRmemcheck.pointsJ1 = 0;
        NRmemcheck.pointsJ2 = 0;
        NRmemcheck.pointsIA = 0;
        Debug.Log(NRmemcheck.points);
        NRmemcheck.AfficherPoints();
        NRmemcheck.Affichepoints.text = NRmemcheck.AfficherPoints();
        NRmemcheck.AfficherPointsJ1();
        NRmemcheck.AffichepointsJ1.text = NRmemcheck.AfficherPointsJ1();
        NRmemcheck.AfficherPointsJ2();
        NRmemcheck.AffichepointsJ2.text = NRmemcheck.AfficherPointsJ2();
        NRmemcheck.AfficherVies();
        NRmemcheck.Affichevies.text = NRmemcheck.AfficherVies();
        Carte1.SetActive(true);
        Carte2.SetActive(true);
        Carte3.SetActive(true);
        Carte4.SetActive(true);
        Carte5.SetActive(true);
        Carte6.SetActive(true);
        Carte7.SetActive(true);
        Carte8.SetActive(true);
        Carte9.SetActive(true);
        Carte10.SetActive(true);
        Carte11.SetActive(true);
        Carte12.SetActive(true);
        Carte13.SetActive(true);
        Carte14.SetActive(true);
        Carte15.SetActive(true);
        Carte16.SetActive(true);
        Carte17.SetActive(true);
        Carte18.SetActive(true);
        Carte19.SetActive(true);
        Carte20.SetActive(true);
        Carte21.SetActive(true);
        Carte22.SetActive(true);
        Carte23.SetActive(true);
        Carte24.SetActive(true);
        Carte25.SetActive(true);
        Carte26.SetActive(true);
        Carte27.SetActive(true);
        Carte28.SetActive(true);
        Carte29.SetActive(true);
        Carte30.SetActive(true);

        carte1.enabled = true;
        carte2.enabled = true;
        carte3.enabled = true;
        carte4.enabled = true;
        carte5.enabled = true;
        carte6.enabled = true;
        carte7.enabled = true;
        carte8.enabled = true;
        carte9.enabled = true;
        carte10.enabled = true;
        carte11.enabled = true;
        carte12.enabled = true;
        carte13.enabled = true;
        carte14.enabled = true;
        carte15.enabled = true;
        carte16.enabled = true;
        carte17.enabled = true;
        carte18.enabled = true;
        carte19.enabled = true;
        carte20.enabled = true;
        carte21.enabled = true;
        carte22.enabled = true;
        carte23.enabled = true;
        carte24.enabled = true;
        carte25.enabled = true;
        carte26.enabled = true;
        carte27.enabled = true;
        carte28.enabled = true;
        carte29.enabled = true;
        carte30.enabled = true;

        Gagné.SetActive(false);
        Perdu.SetActive(false);
        VictoireJ1.SetActive(false);
        VictoireJ2.SetActive(false);
        VictoireIA.SetActive(false);
        Egalité.SetActive(false);
    }


    public void RejouerHD()
    {

        carterandomHD.Mélangeur();
        HDmemcheck.vies = 30;
        HDmemcheck.paires = 0;
        HDmemcheck.points = 0;
        HDmemcheck.pointsJ1 = 0;
        HDmemcheck.pointsJ2 = 0;
        HDmemcheck.pointsIA = 0;
        Debug.Log(HDmemcheck.points);
        HDmemcheck.AfficherPoints();
        HDmemcheck.Affichepoints.text = HDmemcheck.AfficherPoints();
        HDmemcheck.AfficherPointsJ1();
        HDmemcheck.AffichepointsJ1.text = HDmemcheck.AfficherPointsJ1();
        HDmemcheck.AfficherPointsJ2();
        HDmemcheck.AffichepointsJ2.text = HDmemcheck.AfficherPointsJ2();
        HDmemcheck.AfficherVies();
        HDmemcheck.Affichevies.text = HDmemcheck.AfficherVies();
        Carte1.SetActive(true);
        Carte2.SetActive(true);
        Carte3.SetActive(true);
        Carte4.SetActive(true);
        Carte5.SetActive(true);
        Carte6.SetActive(true);
        Carte7.SetActive(true);
        Carte8.SetActive(true);
        Carte9.SetActive(true);
        Carte10.SetActive(true);
        Carte11.SetActive(true);
        Carte12.SetActive(true);
        Carte13.SetActive(true);
        Carte14.SetActive(true);
        Carte15.SetActive(true);
        Carte16.SetActive(true);
        Carte17.SetActive(true);
        Carte18.SetActive(true);
        Carte19.SetActive(true);
        Carte20.SetActive(true);
        Carte21.SetActive(true);
        Carte22.SetActive(true);
        Carte23.SetActive(true);
        Carte24.SetActive(true);
        Carte25.SetActive(true);
        Carte26.SetActive(true);
        Carte27.SetActive(true);
        Carte28.SetActive(true);
        Carte29.SetActive(true);
        Carte30.SetActive(true);
        Carte31.SetActive(true);
        Carte32.SetActive(true);
        Carte33.SetActive(true);
        Carte34.SetActive(true);
        Carte35.SetActive(true);
        Carte36.SetActive(true);
        Carte37.SetActive(true);
        Carte38.SetActive(true);
        Carte39.SetActive(true);
        Carte40.SetActive(true);

        carte1.enabled = true;
        carte2.enabled = true;
        carte3.enabled = true;
        carte4.enabled = true;
        carte5.enabled = true;
        carte6.enabled = true;
        carte7.enabled = true;
        carte8.enabled = true;
        carte9.enabled = true;
        carte10.enabled = true;
        carte11.enabled = true;
        carte12.enabled = true;
        carte13.enabled = true;
        carte14.enabled = true;
        carte15.enabled = true;
        carte16.enabled = true;
        carte17.enabled = true;
        carte18.enabled = true;
        carte19.enabled = true;
        carte20.enabled = true;
        carte21.enabled = true;
        carte22.enabled = true;
        carte23.enabled = true;
        carte24.enabled = true;
        carte25.enabled = true;
        carte26.enabled = true;
        carte27.enabled = true;
        carte28.enabled = true;
        carte29.enabled = true;
        carte30.enabled = true;
        carte31.enabled = true;
        carte32.enabled = true;
        carte33.enabled = true;
        carte34.enabled = true;
        carte35.enabled = true;
        carte36.enabled = true;
        carte37.enabled = true;
        carte38.enabled = true;
        carte39.enabled = true;
        carte40.enabled = true;


        Gagné.SetActive(false);
        Perdu.SetActive(false);
        VictoireJ1.SetActive(false);
        VictoireJ2.SetActive(false);
        VictoireIA.SetActive(false);
        Egalité.SetActive(false);
    }

    public void RejoueruHD()
    {

        carterandomUHD.Mélangeur();
        UHDmemcheck.vies = 50;
        UHDmemcheck.paires = 0;
        UHDmemcheck.points = 0;
        UHDmemcheck.pointsJ1 = 0;
        UHDmemcheck.pointsJ2 = 0;
        UHDmemcheck.pointsIA = 0;
        Debug.Log(UHDmemcheck.points);
        UHDmemcheck.AfficherPoints();
        UHDmemcheck.Affichepoints.text = UHDmemcheck.AfficherPoints();
        UHDmemcheck.AfficherPointsJ1();
        UHDmemcheck.AffichepointsJ1.text = UHDmemcheck.AfficherPointsJ1();
        UHDmemcheck.AfficherPointsJ2();
        UHDmemcheck.AffichepointsJ2.text = UHDmemcheck.AfficherPointsJ2();
        UHDmemcheck.AfficherVies();
        UHDmemcheck.Affichevies.text = UHDmemcheck.AfficherVies();
        Carte1.SetActive(true);
        Carte2.SetActive(true);
        Carte3.SetActive(true);
        Carte4.SetActive(true);
        Carte5.SetActive(true);
        Carte6.SetActive(true);
        Carte7.SetActive(true);
        Carte8.SetActive(true);
        Carte9.SetActive(true);
        Carte10.SetActive(true);
        Carte11.SetActive(true);
        Carte12.SetActive(true);
        Carte13.SetActive(true);
        Carte14.SetActive(true);
        Carte15.SetActive(true);
        Carte16.SetActive(true);
        Carte17.SetActive(true);
        Carte18.SetActive(true);
        Carte19.SetActive(true);
        Carte20.SetActive(true);
        Carte21.SetActive(true);
        Carte22.SetActive(true);
        Carte23.SetActive(true);
        Carte24.SetActive(true);
        Carte25.SetActive(true);
        Carte26.SetActive(true);
        Carte27.SetActive(true);
        Carte28.SetActive(true);
        Carte29.SetActive(true);
        Carte30.SetActive(true);
        Carte31.SetActive(true);
        Carte32.SetActive(true);
        Carte33.SetActive(true);
        Carte34.SetActive(true);
        Carte35.SetActive(true);
        Carte36.SetActive(true);
        Carte37.SetActive(true);
        Carte38.SetActive(true);
        Carte39.SetActive(true);
        Carte40.SetActive(true);
        Carte41.SetActive(true);
        Carte42.SetActive(true);
        Carte43.SetActive(true);
        Carte44.SetActive(true);
        Carte45.SetActive(true);
        Carte46.SetActive(true);
        Carte47.SetActive(true);
        Carte48.SetActive(true);
        Carte49.SetActive(true);
        Carte50.SetActive(true);
        Carte51.SetActive(true);
        Carte52.SetActive(true);
        Carte53.SetActive(true);
        Carte54.SetActive(true);
        Carte55.SetActive(true);
        Carte56.SetActive(true);
        Carte57.SetActive(true);
        Carte58.SetActive(true);
        Carte59.SetActive(true);
        Carte60.SetActive(true);
        Carte61.SetActive(true);
        Carte62.SetActive(true);
        Carte63.SetActive(true);
        Carte64.SetActive(true);
        Carte65.SetActive(true);
        Carte66.SetActive(true);
        Carte67.SetActive(true);
        Carte68.SetActive(true);
        Carte69.SetActive(true);
        Carte70.SetActive(true);
        Carte71.SetActive(true);
        Carte72.SetActive(true);
        Carte73.SetActive(true);
        Carte74.SetActive(true);
        Carte75.SetActive(true);
        Carte76.SetActive(true);
        Carte77.SetActive(true);
        Carte78.SetActive(true);
        Carte79.SetActive(true);
        Carte80.SetActive(true);

        carte1.enabled = true;
        carte2.enabled = true;
        carte3.enabled = true;
        carte4.enabled = true;
        carte5.enabled = true;
        carte6.enabled = true;
        carte7.enabled = true;
        carte8.enabled = true;
        carte9.enabled = true;
        carte10.enabled = true;
        carte11.enabled = true;
        carte12.enabled = true;
        carte13.enabled = true;
        carte14.enabled = true;
        carte15.enabled = true;
        carte16.enabled = true;
        carte17.enabled = true;
        carte18.enabled = true;
        carte19.enabled = true;
        carte20.enabled = true;
        carte21.enabled = true;
        carte22.enabled = true;
        carte23.enabled = true;
        carte24.enabled = true;
        carte25.enabled = true;
        carte26.enabled = true;
        carte27.enabled = true;
        carte28.enabled = true;
        carte29.enabled = true;
        carte30.enabled = true;
        carte31.enabled = true;
        carte32.enabled = true;
        carte33.enabled = true;
        carte34.enabled = true;
        carte35.enabled = true;
        carte36.enabled = true;
        carte37.enabled = true;
        carte38.enabled = true;
        carte39.enabled = true;
        carte40.enabled = true;
        carte41.enabled = true;
        carte42.enabled = true;
        carte43.enabled = true;
        carte44.enabled = true;
        carte45.enabled = true;
        carte46.enabled = true;
        carte47.enabled = true;
        carte48.enabled = true;
        carte49.enabled = true;
        carte50.enabled = true;
        carte51.enabled = true;
        carte52.enabled = true;
        carte53.enabled = true;
        carte54.enabled = true;
        carte55.enabled = true;
        carte56.enabled = true;
        carte57.enabled = true;
        carte58.enabled = true;
        carte59.enabled = true;
        carte60.enabled = true;
        carte61.enabled = true;
        carte62.enabled = true;
        carte63.enabled = true;
        carte64.enabled = true;
        carte65.enabled = true;
        carte66.enabled = true;
        carte67.enabled = true;
        carte68.enabled = true;
        carte69.enabled = true;
        carte70.enabled = true;
        carte71.enabled = true;
        carte72.enabled = true;
        carte73.enabled = true;
        carte74.enabled = true;
        carte75.enabled = true;
        carte76.enabled = true;
        carte77.enabled = true;
        carte78.enabled = true;
        carte79.enabled = true;
        carte80.enabled = true;


        Gagné.SetActive(false);
        Perdu.SetActive(false);
        VictoireJ1.SetActive(false);
        VictoireJ2.SetActive(false);
        VictoireIA.SetActive(false);
        Egalité.SetActive(false);
    }
}
